#My First Workflow

name: workflow1
on: 
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: echo "hello from Gagan"
      - name: step2
        run: cat /etc/os-release
## Name is not important in a step
      - run: uname -a
      
        
