#My First Workflow

name: workflow1
on: 
  workflow_dispatch:
  push:
  pull_request:
env:
   greetings: "Good Morning"
   name: "Mark"
   lastname: "Jack1"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      greetings: "hello"
    steps: 
      - name: step1
        run: |
          echo "$greetings ! from $name . $name created this file under repo ${{ GITHUB.REPOSITORY }} and its running on OS ${{ RUNNER.OS }}"
          echo Application name is ${{ vars.APP_NAME }} and password for the same is ${{ secrets.SERVER_PASSWORD }}
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }} "
          sleep 2
        env:
          name: Gagandeep
          greetings: "hi"
      - name: step2 for testing
        if: github.event_name == 'push'
        run: |
          cat /etc/os-release
          sleep 2
          hostname
          echo "$greetings ! from $name"
          touch /tmp/gagandeep1
          
## Name is not important in a step
      - run: uname -a
  test:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    env:
      lastname: "singh"
    steps: 
     - name: step1
       run: |
          echo "$greetings ! from $name $lastname. $name created this file"
          ech " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }} "
          sleep 2 
     - name: step2
       if: ${{ steps.step1.conclusion == 'failure' }} 
       run: |
          echo step1 failed
     - name: step3
       run: |
          echo step3          
  stage:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ always() }}
    needs: test
    env:
      lastname: "singh"
    steps: 
     - name: step1
       run: |
          echo "$greetings ! from $name $lastname. $name created this file"
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }} "
          sleep 10              
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: stage
    env:
      lastname: "singh"
    steps: 
     - name: step1
       run: |
          echo "$greetings ! from $name $lastname. $name created this file"
          echo " ${{ vars.APP_NAME }} is hosted on ${{ vars.SERVER_NAME }} "
          sleep 10
       env:
          name: Gagandeep
     - name: step2 for testing
       run: |
          cat /etc/os-release
          sleep 10
          hostname
          echo "$greetings ! from $name"
          touch /tmp/gagandeep1
  notify:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy
    steps: 
     - name: Notification email
       run: echo build run status        
